import Navabr from "@/components/hero/Navabr";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "IMS",
  description: "Generated by Inventory Management System",
  type: "website",
  authors: [
    { name: "Masud" },
    { name: "masud", url: "https://github.com/masud-pervez" },
  ],
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navabr />
        {children}
      </body>
    </html>
  );
}
