"use client";
import Navabr from "@/components/Navabr";
import "./globals.css";
import "aos/dist/aos.css";
import Footer from "@/components/Footer";
import { useEffect, useState } from "react";
import Aos from "aos";
import Loading from "@/components/Loading";

export default function RootLayout({ children }) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 200);
    Aos.init();
  }, []);

  return (
    <html lang="en">
      <body className="scroll-smooth">
        {loading ? (
          <Loading />
        ) : (
          <>
            <Navabr />
            {children}
            <Footer />
          </>
        )}
      </body>
    </html>
  );
}

// export const metadata = {
//   title: "IMS",
//   description: "Generated by Inventory Management System",
//   type: "website",
//   authors: [
//     { name: "Masud" },
//     { name: "masud", url: "https://github.com/masud-pervez" },
//   ],
//   icons: {
//     icon: "/favicon.png",
//     shortcut: "/favicon.png",
//   },
// };
